# This is a basic workflow to help you get started with Actions

name: tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths:
      - '**/.py'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**/*.py'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pytest:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov coverage-badge

      - name: Run tests
        run: |
          pytest -v --cov=core --cov=ui --cov-report=xml --cov-report=term-missing > pytest-coverage.txt

      - name: Pytest coverage comment
        if: github.event_name == 'pull_request'
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          pytest-xml-coverage-path: ./coverage.xml
          title: "Code coverage report"
          badge-title: "Coverage"

      - name: Generate Coverage Badge
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          coverage-badge -o coverage.svg -f
          
      - name: Commit and Push Badge
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        shell: powershell
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add coverage.svg
          $status = git status --porcelain
          
          if ($status) {
            Write-Host "The badge has changed, we're writing a commit..."
            git commit -m "Update coverage badge [skip ci]"
            git push
          } else {
            Write-Host "There are no changes in coverage, skipping the commit."
          }
